"use client";
import { useState } from "react";
import useSWR from "swr";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
const fetcher = (url: string) => fetch(url).then((res) => res.json());
interface AlertRow { id: string; type: string; severity: string; detail: string; raisedAt: string; intern: { user: { name: string } } }
export default function SupervisorAlertsPage() { const { data, mutate } = useSWR<{ alerts: AlertRow[] }>("/api/alerts", fetcher); const [notes, setNotes] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); async function refresh() { setBusy(true); const response = await fetch("/api/alerts", { method: "POST" }); setBusy(false); response.ok ? (toast.success("Alert rules evaluated."), mutate()) : toast.error("Unable to evaluate alerts."); } async function resolve(id: string) { const response = await fetch(`/api/alerts/${id}/resolve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note: notes[id] }) }); const result = await response.json(); response.ok ? (toast.success("Alert resolved."), mutate()) : toast.error(result.error); }
  return <div className="flex flex-col gap-4 p-4"><div className="flex items-center justify-between"><h1 className="font-heading text-xl font-bold">Alerts</h1><Button size="sm" variant="outline" onClick={refresh} disabled={busy}>{busy ? "Checking…" : "Refresh rules"}</Button></div>{data?.alerts.length ? data.alerts.map((alert) => <article key={alert.id} className="rounded-xl border bg-card p-4"><div className="flex justify-between gap-2"><p className="font-semibold">{alert.intern.user.name}</p><Badge variant={alert.severity === "HIGH" ? "destructive" : "secondary"}>{alert.severity}</Badge></div><p className="mt-2 text-sm">{alert.detail}</p><p className="mt-1 text-xs text-muted-foreground">{alert.type.replaceAll("_", " ")} · {new Date(alert.raisedAt).toLocaleDateString()}</p><Textarea className="mt-3" placeholder="Resolution note (required)" value={notes[alert.id] ?? ""} onChange={(event) => setNotes((old) => ({ ...old, [alert.id]: event.target.value }))} /><Button className="mt-2 w-full" size="sm" disabled={(notes[alert.id]?.trim().length ?? 0) < 3} onClick={() => resolve(alert.id)}>Resolve Alert</Button></article>) : <p className="rounded-xl border p-6 text-center text-sm text-muted-foreground">No active alerts.</p>}</div>; }
