"use client";
import useSWR from "swr";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
const fetcher = (url: string) => fetch(url).then((res) => res.json());
interface Notice { id: string; title: string; body: string; readAt: string | null; createdAt: string }
function decode(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const raw = atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from([...raw].map((char) => char.charCodeAt(0))); }
export function NotificationFeed() { const { data, mutate } = useSWR<{ notifications: Notice[] }>("/api/notifications", fetcher); async function read(id: string) { await fetch("/api/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); mutate(); } async function enablePush() { try { if (!("serviceWorker" in navigator) || !("PushManager" in window)) throw new Error("Push is not supported by this browser."); const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Notification permission was not granted."); const registration = await navigator.serviceWorker.ready; const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (!publicKey) throw new Error("Push is not configured."); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: decode(publicKey) }); await fetch("/api/notifications/subscribe", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); toast.success("Push notifications enabled."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to enable push."); } }
  return <div className="flex flex-col gap-3"><Button variant="outline" onClick={enablePush}>Enable Push Notifications</Button>{data?.notifications.length ? data.notifications.map((notice) => <button key={notice.id} onClick={() => read(notice.id)} className={`rounded-xl border p-4 text-left ${notice.readAt ? "bg-card" : "bg-accent"}`}><p className="font-semibold">{notice.title}</p><p className="text-sm">{notice.body}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(notice.createdAt).toLocaleString()}</p></button>) : <p className="rounded-xl border p-6 text-center text-sm text-muted-foreground">No notifications yet.</p>}</div>; }
